# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0002_heroinfo'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bookinfo',
            managers=[
                ('books', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='image',
            field=models.ImageField(null=True, upload_to='booktest', verbose_name='图片'),
        ),
    ]
